# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and run integration tests 

on:
  push:
    branches: [ "staging" ]


jobs:
  build_unit_tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo 
      uses: actions/checkout@v4
    - name: Setup .NET version  6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Execute Integration Tests
      run: dotnet test HouseRentingSystem.Tests/HouseRentingSystem.Tests.csproj --no-build --verbosity normal
